apiVersion: skaffold/v4beta2
kind: Config
metadata: 
  name: local-dev
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts: 
    - image: ashura/django
      context: src/ashura
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "**/*.py"
    - image: indra/nodejs
      context: src/indra
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: zetsu/nodejs
      context: src/zetsu
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"

deploy:
  kubectl: {}
manifests:
  kustomize:
    paths:
      - ./k8s/

  