apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.8.1
          ports:
            - containerPort: 2181  # ZooKeeper port
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"  # ZooKeeper client port
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
---
# Services for ZooKeeper and Kafka
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181
