apiVersion: v1
kind: PersistentVolume
metadata:
  name: zetsu-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/zetsu/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zetsu-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi

