apiVersion: v1
kind: ConfigMap
metadata:
  name: zetsu-config
data:
  MONGO_INITDB_ROOT_USERNAME: "zetsu-user"
  MONGO_INITDB_DATABASE: "zetsu-db"
  MONGO_HOST: "zetsu-db-service"
  MONGO_PORT: "27017"
---
apiVersion: v1
kind: Secret
metadata:
  name: zetsu-secret
type: Opaque
data:
  # This should **not** be in version control
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
