apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashura-app-deployment
  labels:
    app: ashura
spec:
  replicas: 1 # number of replicas to run
  selector:
    matchLabels:
      app: ashura
  template:
    metadata:
      labels:
        app: ashura
    spec:
      initContainers:
        - name: ashura-db-check
          image: postgres:14
          command: ['sh', '-c',
            'until pg_isready 
              -h $POSTGRES_HOST 
              -p $POSTGRES_PORT 
              -U $POSTGRES_USER 
              -d $POSTGRES_DB ;
            do 
              echo "waiting for PostgresDB"; 
              sleep 2; 
            done;
            echo "PostgresDB is ready!";'
          ]
          envFrom:
            - configMapRef:
                name: ashura-config
      containers:
        - name: ashura
          image: ashura/django
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 8000 # port exposed by the container
          envFrom:
            - configMapRef:
                name: ashura-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ashura-secret
                  key: POSTGRES_PASSWORD
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ashura-service
spec:
  selector:
    app: ashura
  ports:
    - name: http
      protocol: TCP
      port: 8000 # port exposed by the service
      targetPort: 8000 # port exposed by the container
  type: ClusterIP # type of the service

