apiVersion: v1
kind: ConfigMap
metadata:
  name: ashura-config
data:
  POSTGRES_HOST: "ashura-db-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "ashura-db"
  POSTGRES_USER: "ashura-user"
---
apiVersion: v1
kind: Secret
metadata:
  name: ashura-secret
type: Opaque
data:
  # This should **not** be in version control
  POSTGRES_PASSWORD: cGFzc3dvcmQ=