apiVersion: batch/v1
kind: Job
metadata:
  name: ashura-db-migrate
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      initContainers:
        - name: ashura-db-check
          image: postgres:14
          command: ['sh', '-c',
            'until pg_isready 
              -h $POSTGRES_HOST 
              -p $POSTGRES_PORT 
              -U $POSTGRES_USER 
              -d $POSTGRES_DB ;
            do 
              echo waiting for database; 
              sleep 2; 
            done;
            echo database is ready;'
          ]
          envFrom:
            - configMapRef:
                name: ashura-config
      containers:
        - name: db-migrate
          image: ashura/django
          command: ["python3",  "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: ashura-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ashura-secret
                  key: POSTGRES_PASSWORD
      restartPolicy: Never
